# Generated by Django 3.2 on 2023-01-05 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form1',
        ),
        migrations.RemoveField(
            model_name='form2',
            name='Family_total_income_level',
        ),
        migrations.RemoveField(
            model_name='form2',
            name='last_level_of_studying',
        ),
        migrations.DeleteModel(
            name='Scholarship',
        ),
        migrations.DeleteModel(
            name='Form2',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
